### PR TITLE
Fix some nits in markdown files

### PR DESCRIPTION
**Pull request by dthaler**

### CODE REVIEW

**Review by paulcretu — APPROVED** [review]
Thanks @dthaler!

**Comment by dthaler** [comment]
@paulcretu any ideas on the heroku status?

**Comment by paulcretu** [comment]
Yeah been running into a problem with status checks (made a new issue here documenting what's going on https://github.com/orcasound/orcasite/issues/559)

I'll override to get this one merged. I also added you to the repo so you can make feature branches directly on the repo instead of from a fork, should avoid this problem in the future

**Pull request merged**
